### ISSUE TITLE
Please, add a Readme with some basic setup information

### ISSUE THREAD

**Issue by SaulDoesCode** [driusan/dkim#1]
How far I got
* golang setup
* letsencrypt tls setup
* chasquid configured and running

now...

```bash
go get github.com/driusan/dkim
cd $GOPATH/src/github.com/driusan/dkim/cmd/dkimkeygen
go build
mv dkimkeygen /bin
cd $GOPATH/src/github.com/driusan/dkim/cmd/dkimsign
go build
mv dkimsign /bin
cd $GOPATH/src/github.com/driusan/dkim/cmd/dkimverify
go build
mv dkimverify /bin
```

I ran dkimkeygen and out plopped two files ``dns.txt`` which is probably what needs to be put in the dns records, alongside ``private.pem``, which I know is some sort of certificate but from here on out I'm not sure how to bang everything together in a way that makes my emails have valid DKIM signatures.

Send Help, many thanks.

**Comment by driusan** [comment]
I'll try and add a README this weekend, but the tools are effectively intended to communicate via stdin/stdout and exit codes. The dns.txt is, indeed, the txt record that should be setup at selector._domainkey.example.com for some selector of your choice.

I've never used chasquid, but it looks like dkimverify would fit in with the post-data hook. 

Following the example in their source, you would want to do something like:

```
if command -v dkimverify >/dev/null; then
        if ! dkimverify < "$TF" ; then
                echo "X-DKIM-Verify: Failed verification"
        fi
        echo "X-DKIM-Verify: pass"
fi
```

In order to add an X-DKIM-Verify header to the incoming email. 

(Note that according to the DKIM standard you *shouldn't* reject an email if the verification fails. Also, I haven't tried this, I just wrote it on a GitHub comment box, so it might have syntax errors or other problems.)

Signing outgoing mail is more complicated, because I can't find any hooks that chasquid has to invoke a script before sending data. dkimsign reads from stdin and writes a signed version to stdout. 

I use it as part of a pipe on 9front with the parameters "dkimsign -h From:Subject:To -s selector -d example.com -key /absolute/path/private.pem" where /absolute/path/private.pem is the path to the private.pem file you generated to go with public key encoded in dns.txt, 'selector' matches the 'selector' part of the DNS entry, and example.com is the domain. 

I emailed the chasquid developer to ask him if there's any pre-send hook (I didn't see any) where this would work, I'll let you know if I hear back.

**Comment by driusan** [comment]
(Note that you can also test the DNS part by sending an unsigned email to yourself, copying the raw email to a file, and then playing with the dkimsign options locally and redirecting to a file, then running dkimverify on the file that you redirected to.)

**Comment by SaulDoesCode** [comment]
Wonderful, thank you!

**Comment by SaulDoesCode** [comment]
I'm now trying to integrate DKIM signing into my personal fork of [MailYak](https://github.com/SaulDoesCode/mailyak/commit/bcd59854df6bb86fca16530e2bcf8cb33a819fdc) using this library.

...
It actually worked!! 😄 👍 Thanks for writing this project, alongside chasquid, I now have a way to send cerified and stamped emails practically for free; without having to have a separate mail server and all that terrible configuration and heavan forbid dockerizing every little function.

**Comment by SaulDoesCode** [comment]
Ah good, the readme is there, thanks a lot. 👍
